---
atlas-fesom-grids-path:   ""     # Extra directories or files to search for Fesom grids, separated by ':'
atlas-fesom-caching:      false  # Enable runtime caching of data files if not present in atlas-data-path
...
